version: '3.8'

services:
  gardenio:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL:-postgresql://gardenio:gardenio123@db:5432/gardenio}
      - SESSION_SECRET=${SESSION_SECRET:-your-super-secret-session-key-change-in-production}
    volumes:
      - uploads:/app/uploads
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=gardenio
      - POSTGRES_USER=gardenio
      - POSTGRES_PASSWORD=gardenio123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
  uploads: