name: Build Android App

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: npm ci

    - name: Install Capacitor
      run: |
        npm install -g @capacitor/cli
        npm install @capacitor/core @capacitor/android

    - name: Build web app
      run: npm run build

    - name: Initialize Capacitor
      run: |
        npx cap init GardenIO io.garden.app --web-dir=dist/public
        npx cap add android

    - name: Update Capacitor configuration
      run: |
        cat > capacitor.config.ts << EOF
        import { CapacitorConfig } from '@capacitor/cli';

        const config: CapacitorConfig = {
          appId: 'io.garden.app',
          appName: 'GardenIO',
          webDir: 'dist/public',
          bundledWebRuntime: false,
          server: {
            androidScheme: 'https'
          },
          plugins: {
            SplashScreen: {
              launchShowDuration: 2000,
              backgroundColor: '#ffffff',
              androidScaleType: 'CENTER_CROP',
              showSpinner: false
            }
          }
        };

        export default config;
        EOF

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew

    - name: Build APK
      working-directory: android
      run: ./gradlew assembleDebug

    - name: Build AAB (Release)
      if: startsWith(github.ref, 'refs/tags/')
      working-directory: android
      run: ./gradlew bundleRelease

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: gardenio-debug.apk
        path: android/app/build/outputs/apk/debug/app-debug.apk

    - name: Upload AAB artifact
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: gardenio-release.aab
        path: android/app/build/outputs/bundle/release/app-release.aab

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          android/app/build/outputs/apk/debug/app-debug.apk
          android/app/build/outputs/bundle/release/app-release.aab
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}