name: Build Android App (Simple)

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install dependencies
      run: npm ci

    - name: Build web app
      run: npm run build

    - name: Install Capacitor globally
      run: npm install -g @capacitor/cli

    - name: Install Capacitor packages
      run: npm install @capacitor/core @capacitor/android

    - name: Create capacitor config
      run: |
        cat > capacitor.config.json << 'EOF'
        {
          "appId": "io.garden.app",
          "appName": "GardenIO",
          "webDir": "dist/public",
          "bundledWebRuntime": false,
          "server": {
            "androidScheme": "https"
          }
        }
        EOF

    - name: Initialize Capacitor
      run: cap init --config capacitor.config.json

    - name: Add Android platform
      run: cap add android

    - name: Sync Capacitor
      run: cap sync android

    - name: Set Android SDK path
      run: |
        echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=/usr/local/lib/android/sdk" >> $GITHUB_ENV

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept Android licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Build APK
      working-directory: android
      run: |
        chmod +x gradlew
        ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: gardenio-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: android/app/build/outputs/apk/debug/app-debug.apk
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}